environment:
  CHAT_WEBHOOK_PATH:
    secure: Oawgup4p18hTqsE2qGz07QLvtL/xrDiGFmqs9ebmXATs6t/Mp6L/sVS0XbAgmXhuOtZ8Q3KDC//q0ViBEnNiaEcZg3cI3GGPchtIQYjAozEC+3d3SXQY9zcSymAPgYsmc1TOsC+3BbuYXskoTu6myDbRPfh2i0YuU2lr0SRRbGS+68fGhBiPhZtkS6DOfDfu
    
install:
  - ps: Install-Product node ''
  - ps: $env:ELECTRON_NO_ATTACH_CONSOLE = 1
  - ps: Invoke-WebRequest "https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-windows-x64-release.zip" -OutFile "dart.zip"
  - ps: Invoke-WebRequest "https://storage.googleapis.com/dart-archive/channels/dev/release/latest/sdk/dartsdk-windows-x64-release.zip" -OutFile "dart-dev.zip"
  - ps: 7z.exe x dart.zip | out-null
  - ps: 7z.exe x -odev dart-dev.zip | out-null
  - git clone -b beta https://github.com/flutter/flutter.git
  - cd flutter
  - git worktree add ..\dev\flutter origin/master
  - cd ..
  - ps: $env:FLUTTER_ROOT = "$pwd\flutter"
  - ps: $env:PATH_STABLE = "$pwd\dart-sdk\bin;$pwd\flutter\bin"
  - ps: $env:PATH_UNSTABLE = "$pwd\dev\dart-sdk\bin;$pwd\dev\flutter\bin"
  - flutter\bin\flutter config --no-analytics
  - dart-sdk\bin\dart --version
  - flutter\bin\flutter --version
  - dev\dart-sdk\bin\dart --version
  - dev\flutter\bin\flutter --version
  - node --version
  - npm --version

build_script:
  - npm install --depth 0 --silent
  - npm run vscode:prepublish --silent
  - npm run lint --silent

test_script:
- npm test

on_failure:
  - ps: $env:APPVEYOR_RESULT = 1

on_finish:
  - npm run post_result_to_chat
